name: Deploy Components to Testnet
on:
  push:
    branches: [develop]
jobs:
  deploy-mainnet:
    uses: NEARBuilders/bos-workspace/.github/workflows/deploy.yml@main
    with:
      bw-legacy: false
      build-env: "testnet"
      deploy-env: "testnet"
      app-name: "commons"
      deploy-account-address: buildcommons.testnet
      signer-account-address: buildcommons.testnet
      signer-public-key: ed25519:5jxC3eDeR8bxhuxG5t6QFmCMK5Y8xPRE9EcPfTDrNH8W
    secrets:
      SIGNER_PRIVATE_KEY: ${{ secrets.TESTNET_SIGNER_PRIVATE_KEY }}
